name: deploy-app

on:
  push:
    branches:
      - main
      - feature-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Step
        run: echo "Deploying the app configuration"
