name: PostgreSQL Service Test

on:
  push:
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U user -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install netcat
        run: sudo apt-get update && sudo apt-get install -y netcat-openbsd

      - name: Wait for PostgreSQL using nc
        run: |
          echo "Waiting for PostgreSQL to be ready on port 5432..."
          for i in {1..30}; do
            if ! nc -z localhost 5432; then
              echo "PostgreSQL not ready yet. Retrying in 1 second..."
              sleep 1
            else
              echo "PostgreSQL is ready!"
              exit 0
            fi
          done
          echo "PostgreSQL did not become ready in time." >&2
          exit 1

      - name: Connect to PostgreSQL and run a command
        run: |
          sudo apt-get install -y postgresql-client
          PGPASSWORD=password psql -h localhost -U user -d testdb -c '\l'
