name: PostgreSQL Service

on:
  push:
    # Automatically when a .yml file is changed and pushed.
    # paths:
    #   - '**.yml'
  # Manually by clicking "Run workflow" in the GitHub Actions UI.
  workflow_dispatch:

jobs:
  test-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for PostgreSQL port using  Netcat (nc) Check
        run: |
          echo "Waiting for PostgreSQL to be ready on port 5432..."
          for i in {1..30}; do
            if nc -z localhost 5432; then
              echo "PostgreSQL is up!"
              break
            fi
            echo "PostgreSQL not ready yet... retrying in 1s"
            sleep 1
          done

      - name: Test PostgreSQL Connection
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          PGPASSWORD=password psql -h localhost -U user -d testdb -c '\l'
