name: GitHub Secret Workflow

on:
  push:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Show Secret
        run: echo "The secret is $SECRET"
        env:
          SECRET: ${{ secrets.SECRET }}
