name: Use GitHub Secret

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Secret (Masked)
        run: |
          echo "The secret is ${{ secrets.SECRET }}"
        shell: bash
