name: GitHub Secret Workflow

on:
  push:
    branches: [main]

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print a masked secret
        run: echo "The secret is \${{ secrets.SECRET }}"
